"""Renders a reviewed questionnaire as a downloadable DOCX or CSV — the F4
"export as DOCX/CSV" step. Free-plan exports get a watermark footer; nothing
here ever calls out to a customer's system, it only produces a file."""

import csv
import io

from docx import Document
from docx.shared import Pt


def build_docx(
    workspace_name: str,
    filename: str,
    rows: list[dict],
    watermark: bool,
) -> bytes:
    doc = Document()
    doc.add_heading(f"{workspace_name}: Security Questionnaire Responses", level=1)
    doc.add_paragraph(f"Source: {filename}")
    doc.add_paragraph("Generated by Tracyn. Reviewed and approved by a human before export.")

    if watermark:
        note = doc.add_paragraph()
        run = note.add_run("FREE PLAN: evaluation copy, not for external distribution. Upgrade to remove this notice.")
        run.italic = True
        run.font.size = Pt(9)

    for row in rows:
        doc.add_heading(row["question_text"], level=2)
        doc.add_paragraph(row["final_answer"] or row["draft_answer"] or "(no answer drafted)")
        if row["evidence_event_ids"]:
            evidence = doc.add_paragraph()
            evidence.add_run("Evidence: ").bold = True
            evidence.add_run(", ".join(row["evidence_event_ids"]))

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_csv(rows: list[dict]) -> bytes:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Question", "Answer", "Status", "Evidence Event IDs"])
    for row in rows:
        writer.writerow(
            [
                row["question_text"],
                row["final_answer"] or row["draft_answer"] or "",
                row["status"],
                ", ".join(row["evidence_event_ids"]),
            ]
        )
    return buf.getvalue().encode("utf-8")
